const list = [
  
    {
      id : 1,
      title :"Ek Din Zindagi Badal Jayegi",
      author : "by Saranya Umakanthan|1 March 2022",
      price :159,
      img : "https://m.media-amazon.com/images/I/418LWaw-iAL._AC_SF480,480_.jpg",
      amount : "1",
    },
    {
      id : 2,
      title :"A Little Princess",
      author : " by Frances Hodgson Burnett |1 October 2018",
      price :149,
      img : "https://m.media-amazon.com/images/I/61VlRb+9PJL._SX342_SY445_.jpg",
      amount : "1",
    },
    {
      id : 3,
      title :"No Matter What",
      author : "by Rohit Dawesar|1 November 2020",
      price :209,
      img : "https://m.media-amazon.com/images/I/51Gjcc9570L._AC_SF480,480_.jpg",
      amount : "1",
    },
    {
      id : 4,
      title :"The Little Prince",
      author : "by Antoine De Saint-Exupéry |1 March 2016",
      price :188,
      img : "https://m.media-amazon.com/images/I/41lXGsGtrzS._AC_SF480,480_.jpg",
      amount : "1",
    },
    {
      id : 5,
      title :"The Enchanted Castle",
      author : "by E. Nesbit|1 December 2019",
      price :159,
      img : "https://images-eu.ssl-images-amazon.com/images/I/71x2t6LB4AL._AC_UL165_SR165,165_.jpg",
      amount : "1",
    },
    {
      id : 6,
      title :"A Doll’s House",
      author : "by Henrik Ibsen  | 1 February 2021",
      price :129,
      img : "https://images-eu.ssl-images-amazon.com/images/I/71Q3Fi-+0UL._AC_UL165_SR165,165_.jpg",
      amount : "1",
    },
    {
      id :7 ,
      title :"Until Love Sets Us Apart",
      author : "by Aditya Nighhot  | 15 August 2018",
      price :179,
      img : "https://m.media-amazon.com/images/I/41eZqCEPbIL._AC_SF480,480_.jpg",
      amount : "1",
    },
   
    {
      id : 8,
      title :"Birds of India",
      author : "by Bikram Grewal ,| 2 May 2016",
      price :1139,
      img : "https://m.media-amazon.com/images/I/711tge7Y4yL._SY385_.jpg",
      amount : "1",
    },
    {
      id : 9,
      title :"The Power of A Positive Attitude",
      author : "by Roger Fritz  | 1 September 2020s",
      price :134,
      img : "https://m.media-amazon.com/images/I/41i6swNIigL._AC_SF480,480_.jpg",
      amount : "1",
    },
    {
      id : 10,
      title :"Aap Kar Sakte Hai",
      author : "by 	George Mathew Adams|25 April 2024",
      price :143,
      img : "https://m.media-amazon.com/images/I/41QEQ2rKNWL._AC_SF480,480_.jpg",
      amount : "1",
    },
    {
      id : 11,
      title :"One Day, Life Will Change",
      author : "by Saranya Umakanthan  | 1 March 2020",
      price :179,
      img : "https://m.media-amazon.com/images/I/61zU3jQhlCL._SX342_SY445_.jpg",
      amount : "1",
    },
    {
      id : 12,
      title :"Aapke Avchetan Mann Ki Shakti",
      author : "by Joseph Murphy  | 1 December 2017",
      price :149,
      img : "https://images-eu.ssl-images-amazon.com/images/I/71ox+pwkgrS._AC_UL165_SR165,165_.jpg",
      amount : "1",
    },
    {
      id : 13,
      title :"Personality Development",
      author : "by D. P. Sabharwal  | 1 May 2015",
      price :139,
      img : "https://images-eu.ssl-images-amazon.com/images/I/715g5BUwd5L._AC_UL165_SR165,165_.jpg",
      amount : "1",
    },
    {
      id : 14,
      title :"Start Living Again",
      author : "by Saranya Umakanthan| 15 March 2024",
      price :170,
      img : "https://m.media-amazon.com/images/I/41awZiaiP5L._SX342_SY445_.jpg",
      amount : "1",
    },
    {
      id : 15,
      title :"Safalta Ke Sutra",
      author : "by William Walker Atkinson  | 1 May 2021",
      price :109,
      img : "https://m.media-amazon.com/images/I/81f4-7-Ur4L._SY385_.jpg",
      amount : "1",
    },
    {
      id : 16,
      title :"Satyayodha Kalki",
      author : "by Kevin Missal|13 July 2017",
      price :101,
      img : "https://m.media-amazon.com/images/I/81ICIPheXtL._SY385_.jpg",
      amount : "1",
    },
    {
      id : 17,
      title :"Before You Start Up ",
      author : "by Pankaj Goyal  | 1 March 2020",
      price :159,
      img : "https://m.media-amazon.com/images/I/51uWnCyxfzL._AC_SF480,480_.jpg",
      amount : "1",
    },
    {
      id : 18,
      title :"Ameer Hona Aapka Adhikar",
      author : "by Joseph Murphy  | 1 February 2021",
      price :89,
      img : "https://images-eu.ssl-images-amazon.com/images/I/81mLE0O8KfL._AC_UL165_SR165,165_.jpg",
      amount : "1",
    },
    {
      id : 19,
      title :"Five Children and It",
      author : "by E. Nesbit  | 1 May 2021",
      price :150,
      img : "https://m.media-amazon.com/images/I/61pT37-wc7L._AC_SF480,480_.jpg",
      amount : "1",
    },
    {
      id : 20,
      title :"Right From The Start ",
      author : "by Prachi Gupta and Sanchit Garg  | 1 August 2018",
      price :160,
      img : "https://m.media-amazon.com/images/I/51aQEJ1iQbL._AC_SF480,480_.jpg",
      amount : "1",
    },
    {
      id : 21,
      title :"You Belong With Me",
      author : "by Shuchi Batra  | 29 February 2024",
      price :207,
      img : "https://images-eu.ssl-images-amazon.com/images/I/71duK9QZ3CL._AC_UL165_SR165,165_.jpg",
      amount : "1",
    },
      
    



      
];

export default list;
        